language: python

python:
    - 2.7

virtualenv:
    system_site_packages: true

compiler:
    - g++

before_install:
    - "sudo apt-get -qq update"
    # Non-pip dependency
    - "sudo apt-get install -y libffi-dev libssl-dev python-dev"
    - "pip install --user pyOpenSSL ndg-httpsclient pyasn1"
    - "pip install --user urllib3[secure] --upgrade"
    - "pip install --user requests[security] --upgrade"
    # GalSim dependencies
    - "sudo apt-get install -y libfftw3-dev libav-tools libeigen3-dev cmake"
    - "pip install --user pybind11"
    # Install GalSim
    #- "pip install --user galsim"
   
cache:
    ccache: true
    pip: true

install:
    # Install SLRealizer dependencies
    - "pip install --user -r requirements.txt"

script:
    - "python setup.py install"
    # For getting the full list of dependencies
    #- "pip freeze"
    # Check if it can import slrealizer
    - "python -c 'import slrealizer'"
    - "ls slrealizer/data"
    - "cd slrealizer/tests"
    - "python test_analytical_moments.py"
    - "python test_om10realizer.py"
    - "python test_sdssrealizer.py"

after_success:
    - codecov